# 美妆内容标签分类体系

# 谈论角度标签
talking_angles:
  - "种草"
  - "拔草"
  - "测评"
  - "教程"
  - "开箱"
  - "对比"
  - "空瓶"
  - "试色"
  - "科普"
  - "Vlog"
  - "优惠信息"
  - "心得"

# 使用场景标签
scenarios:
  - "通勤"
  - "约会"
  - "熬夜修护"
  - "健身"
  - "旅行"
  - "婚礼"
  - "职场"
  - "换季"
  - "夏季控油"
  - "冬季保湿"
  - "淡妆"
  - "浓妆"
  - "敏感期"
  - "医美术后"
  - "户外防晒"

# 肤质类型标签
skin_types:
  - "干性"
  - "油性"
  - "混合"
  - "中性"
  - "敏感"
  - "痘痘肌"

# 肤况诉求标签
skin_concerns:
  - "泛红"
  - "闭口"
  - "黑头"
  - "毛孔"
  - "痘印"
  - "暗沉"
  - "细纹"
  - "松弛"
  - "出油"
  - "脱皮"
  - "屏障受损"
  - "水油不平衡"

# 产品类目标签
product_categories:
  - "洁面"
  - "爽肤水"
  - "精华"
  - "乳液"
  - "面霜"
  - "防晒"
  - "面膜"
  - "身体护理"
  - "唇部"
  - "底妆"
  - "眼妆"
  - "唇妆"
  - "头发护理"

# 成分标签
ingredients:
  - "神经酰胺"
  - "玻尿酸"
  - "烟酰胺"
  - "水杨酸"
  - "壬二酸"
  - "A醇"
  - "VC"
  - "角鲨烷"
  - "积雪草"
  - "透明质酸"
  - "胶原蛋白"
  - "果酸"
  - "杏仁酸"
  - "熊果苷"
  - "曲酸"
  - "传明酸"
  - "二裂酵母"
  - "寡肽"
  - "胜肽"
  - "视黄醇"

# 功效标签
benefits:
  - "保湿"
  - "修护"
  - "抗老"
  - "祛痘"
  - "美白提亮"
  - "控油"
  - "舒缓"
  - "防晒"
  - "清洁"
  - "紧致"
  - "淡斑"
  - "去角质"
  - "收毛孔"
  - "抗氧化"

# 情感立场标签
stance:
  - "强种草"
  - "一般种草"
  - "中性"
  - "轻微拔草"
  - "强烈拔草"

# 合规标识标签
compliance_flags:
  - "可能广告/合作"
  - "夸大功效"
  - "医疗化用语"
  - "敏感词"

# 质量标识标签
quality_flags:
  - "ASR低质"
  - "OCR噪声高"
  - "疑似重复"
  - "机器翻译痕迹"
  - "内容过短"
  - "内容不完整"

# 口语化映射词典
slang_mappings:
  skin_types:
    "大干皮": "干性"
    "沙漠皮": "干性"
    "干敏": ["干性", "敏感"]
    "混油": "混合"
    "油痘肌": ["油性", "痘痘肌"]
    "大油田": "油性"
    "敏感肌": "敏感"
  
  talking_angles:
    "无限回购": "种草"
    "强推": "种草"
    "踩雷": "拔草"
    "避雷": "拔草"
    "真香": "种草"
    "翻车": "拔草"
    "平替": "对比"
  
  skin_concerns:
    "烂脸": "痘痘肌"
    "爆痘": "痘痘肌"
    "起皮": "脱皮"
    "搓泥": "屏障受损"